name: Git Cherry Pick

on:
  pull_request:
    branches:
      - release/**

jobs:
  verify-repo-settings:
    name: Verify Repo Settings
    runs-on: ubuntu-latest

    permissions:
      contents: write # Requires write permissions to receive `allow_squash_merge` and `allow_rebase_merge` keys in repository request

    steps:
      - name: Verify Repo Settings
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            if (data.allow_squash_merge != false || data.allow_rebase_merge != false) {
              core.setFailed('Neither "allow_squash_merge" nor "allow_rebase_merge" must be allowed!');
            }

  git-cherry-pick:
    name: Git Cherry Pick
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    needs:
      - verify-repo-settings

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect Difference
        id: diff
        run: echo "commits=$(git log --cherry-pick --right-only --pretty=oneline "origin/main...origin/${{ github.head_ref }}" | awk '{ print $1 }' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Notify Commit Author
        if: ${{ steps.diff.outputs.commits != '' }}
        uses: actions/github-script@v6
        with:
          script: |
            const notifyCommitAuthor = require('.github/scripts/notify-commit-author.js');
            await notifyCommitAuthor({ github, context, commits: '${{ steps.diff.outputs.commits }}' });

      - name: Fail Build
        if: ${{ steps.diff.outputs.commits != '' }}
        run: exit 1
